<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2013-03-12 12:50

$extensionPath = t3lib_extMgm::extPath('themes_settings');
$extensionClassesPath = $extensionPath . 'Classes/';
return array(
	'tx_themessettings_hooks_tslibfecontentpostprocallhook' => $extensionClassesPath . 'Hooks/TsLibFeContentPostProcAllHook.php',
	'tx_themessettings_typoscript_helper' => $extensionClassesPath . 'TypoScript/Helper.php',
);
?>