<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2013-03-13 21:06

$extensionPath = t3lib_extMgm::extPath('dyncss_phpsass');
$extensionClassesPath = $extensionPath . 'Classes/';
return array(
	'tx_dyncssphpsass_parsersass' => $extensionClassesPath . 'ParserSass.php',
	'tx_dyncssphpsass_parserscss' => $extensionClassesPath . 'ParserScss.php',
);
?>