<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2013-06-15 08:51

$extensionPath = t3lib_extMgm::extPath('themes_adapter_directory');
$extensionClassesPath = $extensionPath . 'Classes/';
return array(
	'tx_themesadapterdirectory_domain_model_theme' => $extensionClassesPath . 'Domain/Model/Theme.php',
	'tx_themesadapterdirectory_hooks_tx_themes_domain_repository_themerepository_hook' => $extensionClassesPath . 'Hooks/Tx_Themes_Domain_Repository_ThemeRepository_Hook.php',
);
?>