<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2013-03-14 17:15

$extensionPath = t3lib_extMgm::extPath('themes_adapter_wordpress');
$extensionClassesPath = $extensionPath . 'Classes/';
return array(
	'tx_themesadapterwordpress_controller_renderer' => $extensionClassesPath . 'Controller/Render.php',
	'tx_themesadapterwordpress_domain_model_theme' => $extensionClassesPath . 'Domain/Model/Theme.php',
	'tx_themesadapterwordpress_hooks_tx_themes_domain_repository_themerepository_hook' => $extensionClassesPath . 'Hooks/Tx_Themes_Domain_Repository_ThemeRepository_Hook.php',
);
?>