<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2013-03-12 12:50

$extensionPath = t3lib_extMgm::extPath('themes_fces_fluidcontent_basic');
return array(
);
?>