<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2013-02-24 06:20

$extensionPath = t3lib_extMgm::extPath('dyncss_scss');
$extensionClassesPath = $extensionPath . 'Classes/';
return array(
	'tx_dyncssscss_parser' => $extensionClassesPath . 'Parser.php',
	'tx_dyncssscss_parsercompass' => $extensionClassesPath . 'ParserCompass.php',
);
?>