<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2013-03-12 12:50

$extensionPath = t3lib_extMgm::extPath('themes_builder');
$extensionClassesPath = $extensionPath . 'Classes/';
return array(
	'tx_themesbuilder_controller_buildcontroller' => $extensionClassesPath . 'Controller/BuildController.php',
);
?>