<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2012-09-24 15:17

$extensionPath = t3lib_extMgm::extPath('coreupdate');
$extensionClassesPath = t3lib_extMgm::extPath('coreupdate') . 'Classes/';
return array(
	'tx_coreupdate_controller_extdirectcontroller' => $extensionClassesPath . 'Controller/ExtDirectController.php',
	'tx_coreupdate_hook_reports_versionstatusprovider' => $extensionClassesPath . 'Hook/Reports/VersionStatusProvider.php',
	'tx_coreupdate_lib_helper' => $extensionClassesPath . 'Lib/Helper.php',
	'tx_coreupdate_toolbaritems_updater_item' => $extensionClassesPath . 'ToolbarItems/Updater/Item.php',
);
?>