<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2012-11-03 18:11

$extensionPath = t3lib_extMgm::extPath('dyncss_test');
$extensionClassesPath = t3lib_extMgm::extPath('dyncss_test') . 'Classes/';
return array(
);
?>