<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2012-12-05 07:40

$extensionPath = t3lib_extMgm::extPath('dyncss_less');
$extensionClassesPath = $extensionPath . 'Classes/';
return array(
	'tx_dyncssless_parser' => $extensionClassesPath . 'Parser.php',
);
?>